-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jul 17, 2021 at 01:33 PM
-- Server version: 5.7.27-log
-- PHP Version: 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tesla`
--

-- --------------------------------------------------------

--
-- Table structure for table `resep_masakan`
--

CREATE TABLE `resep_masakan` (
  `id` bigint(20) NOT NULL,
  `Title` text,
  `Ingredients` text,
  `Steps` text,
  `Loves` text,
  `URL` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted__at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `resep_masakan`
--

INSERT INTO `resep_masakan` (`id`, `Title`, `Ingredients`, `Steps`, `Loves`, `URL`, `created_at`, `updated_at`, `deleted__at`) VALUES
(1, 'Ayam goreng tulang lunak', '1 kg ayam (dipotong sesuai selera jangan kecil2 ya)--2 batang serai (memarkan)--4 lembar daun jeruk--7 butir bawang putih (haluskan)--1 sdm ketumbar (haluskan)--3 ruas jari Laos (haluskan)--3 ruas jari kunyit (haluskan)--2 butir kemiri (haluskan)--secukupnya Garam--Secukupnya Air (tuk ukep ayam)--Secukupnya Minyak goreng--', 'Haluskan bumbu2nya (BaPut, ketumbar, kemiri, kunyit, Laos, garam) hingga halus, sisihkan--Campur kan bumbu halus tadi dengan ayam yg sudah dicuci bersih dan sudah dipotong didalam panci presto. Uleni sampai tercampur rata.--Tambahkan air hingga ayam tenggelam semua. Masukkan serai dan daun jeruk nya kedalam rendaman ayam. Tutup panci presto rebus/ ukep presto sampai kurleb 45 menit. Dengan api sedang.--Setelah proses ukep presto selesai, tunggu suhu dingin ruang. Lalu goreng ayam dengan minyak goreng api sedang sampai ayam berwarna kecoklatan.--Matang dan sajikan ayam selagi hangat bersama nasi putih, sambal dgn perasan jeruk nipis, lalapan.--', '1', '/id/resep/4471956-ayam-goreng-tulang-lunak', NULL, NULL, NULL),
(2, 'Ayam cabai kawin', '1/4 kg ayam--3 buah cabai hijau besar--7 buah cabai merah rawit--3 siung bawang putih--2 siung bawang merah--secukupnya Gula--secukupnya Garam--1/4 buah tomat merah--secukupnya Air--secukupnya Minyak goreng--', 'Panaskan minyak di dalam wajan. Setelah minyak panas masukkan ayam yang sudah dipotong dadu. Goreng hingga matang. Lalu tiriskan.--Haluskan bawang putih, bawang merah, cabai hijau dan merah, tomat.--Panaskan minyak didalam wajan. Setelah minyak panas, masukkan bumbu yang sudah halus. Tunggu sampai wangi. Masukkan ayam yang sudah di goreng. Tambahkan air, gula dan garam. Tunggu sampai bumbu meresap di ayam. Sajikan.--', '2', '/id/resep/4473057-ayam-cabai-kawin', NULL, NULL, NULL),
(3, 'Minyak Ayam', '400 gr kulit ayam & lemaknya--8 siung bawang putih kating, cincang kasar--1 ruas jahe, geprek--350 ml minyak goreng--1 sdm ketumbar bubuk--', 'Cuci bersih kulit ayam. Sisihkan--Ambil 50 ml minyak goreng satu bahan yg sudah disiapkan tadi. Tumis jahe hingga harum.--Masukkan kulit ayam, ketumbar dan bawang. Biarkan hingga keluar minyak alaminya sambil diaduk-aduk.--Tambahkan sisa minyak goreng. Masak hingga kulit ayam mengering. Angkat dan saring.--Setelah cukup dingin minyak ayam tadi dapat disimpan dalam wadah kering seperti mason jar/botol. Kalo saya, saya masukkan juga sedikit bawang putih goreng.--Kulit ayam yg sudah digoreng kering tadi bisa dinikmati begitu saja sebagai camilan dengan ditaburi sejumput garam lalu aduk rata.--', '4', '/id/resep/4427438-minyak-ayam', NULL, NULL, NULL),
(4, 'Ayam Saus Hintalu Jaruk', '1/2 Ekor ayam--2 Butir Hintalu Jaruk--1 Buah Cabe merah--1 Buah Cabe hijau--300 gr Tepung terigu--1 bks Merica bubuk--2 Siung Bawang putih--1 Buah jeruk nipis--secukupnya Minyak goreng untuk menumis dan menggoreng--secukupnya Gula, garam dan penyedap rasa--', 'Potong ayam menjadi kotak-kotak ukuran sedang cuci bersih kemudian lumuri perasan jeruk nipis, garam dan merica--Buat adonan tepung untuk melapisi ayam. Adonan A (Tepung terigu, garam, merica, penyedap dan air es) dan adonan B (Tepung terigu, garam, merica dan penyedap)--Masukan daging ayam kedalam adonan A kemudian lapisi dengan adonan B, setelah itu goreng daging kedalam minyak panas sampai berwarna kuning keemasan. Angkat tiriskan--Cincang bawang putih,iris seron cabe merah dan cabe hijau. Lumatkan kuning hintalu jaruk aka telur asin dengan air dingin sampai berbentuk pasta--Tumis bawang putih dan cabe sampai harum, kemudian tuangkan ayam dan pasta kuning telur.--Tambahkan gula, garam, penyedap dan merica secukupnya. Tes rasa dan masal hingga mengental--Angkat dan sajikan bersama nasi putih panas. Selamat mencoba--', '0', '/id/resep/4437475-ayam-saus-hintalu-jaruk', NULL, NULL, NULL),
(5, 'Steak ayam', '300 gr dada ayam fillet--1 sdm air jeruk nipis--secukupnya garam--adonan basah--50 gr terigu--10 gr maizena--1/4 sdt merica--garam--secukupnya air--adonan kering--150 gr terigu--30 gr maizena--1/2 sdt merica bubuk--1/4 sdt kaldu jamur--secukupnya garam--secukupnya minyak goreng--bahan saus jamur--50 gr jamur tiram blender--3 bawang putih cincang halus--20 gr keju parut--1 sdm maizena cairkan dgn air--2 sdm saus tiram--1 sdm kecap manis--1/2 sdt merica halus--secukupnya garam & kaldu jamur--air--bahan pelengkap--buncis dan wortel di kukus--', 'Cuci bersih ayam, iris tipis melebar, rendam dgn garam dan air jeruk nipis 10 menit, cuci--Campur adonan kering, sisihkan--Campur adonan basah, sisihkan--Panaskan minyak goreng dgn api sedang, gulingkan ayam pada adonan kering, lalu celup ke adonan basah, gulingkan lg pada adonan kering, jgn di remas2, kibas2 daging ayam pada adonan kering, lalu goreng di minyak yg banyak dan panas, biarkan krispinya terbentuk dl, jgn di balik2 dl, setelah cukup kering br di balik, goreng smpe matang, tiriskan--Blender jamur tiram kasih air sedikit. tumis bawang putih yg di cincang halus, masukkan jamur yg di blender, masukkan bumbu2 yg lain sampai meresap, lalu tuang maizena yg sdh di cairkan dgn setengah gelas air, aduk2, masukkan keju parut, aduk sampai meletup2, tes rasa, klo sdh sesuai, angkat--Tata dlm piring, ayam goreng tepung dan sayur kukus, siram dgn saus jamur, taburi daun bawang atau parsley jk ada.--', '6', '/id/resep/4472822-steak-ayam', NULL, NULL, NULL),
(6, 'Ayam Saos Asam Manis Simple', '1/4 kg Ayam bagian dada fillet (Potong dadu)--Secukupnya air jeruk nipis utk baluran--1 Bungkus tepung bumbu ayam instan uk besar + campur sedikit tepung terigu--3 Siung b.putih (iris tipis)--3 Siung b.merah (Iris tipis)--1 Buah b.bombay (Iris tipis)--1 Buah tomat uk besar (Haluskan)--3 sdm saos sambal--1 Sdm Saos tiram--Secukupnya Gula & garam--Secukupnya merica bubuk--', 'Lumuri ayam yg sdh dipotong dadu dgn garam & perasan jeruk nipis (diamkan sebentar)--Baluri ayam dengan tepung basah, lanjutkan ke tepung kering, diamkan sebentar--Goreng ayam yg sdh dbaluri tepung sampai kering & matang, angkat tiriskan.--Membuat Saos Asam Manis : -Tumis b.merah & putih (sy suka klo bawang y agak kering)--Masukkan bawang bombay, tumis sebentar.--Masukkan tomat buah yg sdh dihaluskan tdi, tumis lagi pakai api sedang, tambahkan air secukupnya--Masukkan saos sambal, saos tiram, sedikit perasan jeruk nipis, gula, garam & merica (koreksi sampai rasanya terasa asam manis gurih segar)--Masukkan ayam yg sdh digoreng tdi kedalam saos asam manis, diamkan sebentar--Setelah ayam sdh cukup merasap dengan saos asam manisnya matikan api dan siap disajikan dengan nasi putih hangat--', '6', '/id/resep/4472901-ayam-saos-asam-manis-simple', NULL, NULL, NULL),
(7, 'Ayam Bakar Pedas Manis Resep :Nila Sari', '1 Ekor Ayam Broiler Ukuran Jumbo--Bumbu :--5 Siung Bawang Merah--10 Buah Cabe (Optional)--1 Ruas Jahe--1 Ruas Kunyit--Secukupnya Lada Bubuk--Secukupnya Ketumbar--2 Lembar Daun Jeruk--3 Lembar Daun Salam--1 Batang Serai--4 Siung Bawah Putih--Secukupnya Kecap--Secukupnya Gula Merah--Secukupnya Minyak Goreng--Secukupnya Royco--Secukupnya Garam--1 Bungkus Santan Kara--', 'Iris tipis bawang merah dan daun jeruk.--Haluskan cabe, bawang putih, lada, ketumbar, jahe dan kunyit.--Tumis bawang merah hingga wangi.--Masukan bumbu yang telah dihaluskan ke dalam tumisan bawang tumis semua hingga harum.--Masukan serai, daun jeruk dan daun salam masak sedikit tuang santan kara dan tambahkan air.--Kemudian masukan ayam taburi royco, lada dan garam aduk aduk tutup dan tunggu ayam empuk dan air mulai susut tes rasa.--Bakar ayam bisa menggunakan arang, teflon, atau batu bakar (saya memakai grill lebih praktis).--Selamat Mencoba.--', '8', '/id/resep/4472362-ayam-bakar-pedas-manis-resep-nila-sari', NULL, NULL, NULL),
(8, 'Semur Ayam Kentang Ala Mama Kirana', '1/2 Ekor ayam--Kentang--Bumbu Halus :--Bawang putih - bisa di sesuaikan sesuaikan--Bawang merah--Merica--Kemiri--Sedikit biji Pala--Cabai Merah kriting, bila suka pedas--Sedikit jahe--Rempah:--Daun salam--Lengkuas--Sereh--Kapulaga--Kulit manis--Irisan bawang bombay--Irisan tomat--Garam--Kecap manis--Sedikit penyedap rasa--Jeruk nipis untuk ayam--', 'Cuci bersih ayam lalu baluri dengan perasan jeruk nipis--Cuci lagi ayam dan baluri dengan garam lalu rebus sebentar lalu di goreng--Kentang saya goreng bisa di sesuaikan sesuai selera masing²--Tips goreng ayam agar hasil nya tdk keras : di goreng hanya sebentar--Tumis bawang bombay lalu masukan bumbu halus dan masukkan semua rempah + irisan tomat + kecap manis--Setelah bumbu harum masukkan air tunggu gingga mendidih--Tambahkan garam + penyedap rasa apabila kurang manis bisa ditambahkan kecap lagi--Setelah semua sudah sesuai dgn rasa masukkan kentang goreng + ayam goreng--Tunggu kuah hingga menyusut dan kiraa² 5 mnt angkat. Dan terakhir saya taburin bawang goreng bisa disesuaikan jg dgn selera masing². Selesai--', '2', '/id/resep/4472563-semur-ayam-kentang-ala-mama-kirana', NULL, NULL, NULL),
(9, 'Ayam suwir', '300 gram Ayam suwir (sudah direbus/Goreng)--5 siung bawang merah--3 siung bawang putih--1/2 buah tomat--1/2 sdt merica--1/2 sdt terasi--2 buah cabe rawit--2 buah cabe kriting--Secukupnya gula--Secukupnya garam--Secukupnya air--Secukupnya penyedap rasa (Royco)--2 lembar daun salam--1 jari Lengkuas geprek--', 'Haluskan semua bumbu kecuali tomat, lengkuas, Dan daun salam--Siapkan wajan untuk menumis Bumbu, kemudian tuang sedikit minyak Goreng Dan tumis Bumbu yang sudah dihaluskan ditambah daun Salam Dan lengkuas--Setelah tercium bau Bumbu yang ditumis kemudian masukkan tomat yang sudah dipotong potong--Kemudian setelab tomat layu masukkan air secukupnya Dan rasakan kuahnya kalau belum pas bisa ditambahkan penyedap rasa (Royco)--Masukkan ayam yang sudah disuwir Dan aduk--Tunggu sampai meresap Dan air berkurang--Dan sajikan--', '0', '/id/resep/4471653-ayam-suwir', NULL, NULL, NULL),
(10, 'Ayam penyet rumahan', '1 ekr ayam negri cuci bersih ptng beri air jeruk nipis cuci lagi--1 buah jeruk nipis--Bumbu ayam goreng jd,yg bsah. bisa beli di pasar,aku beli 3rb--2 lmbr daun salam--2 lmbr daun jeruk--1 btng sere geprek--Garam secukupnya dan penyedap--secukupnya Minyak goreng--Sambel penyet:--20 buah cabe rawit merah--5 buah cabe merah--2 siung bawang p kating--5 buah bawang merah goreng sebentr--Penyedap dan sedikit gula--', 'Ungkep ayam bersama bumbu jadi, daun salam, daun jeruk, sere,dan garam,tambah sedikit penyedap apinya kecil ajah ya. Lalu tutup--Apabila sudah empuk dan matang goreng dalam minyak panas dan banyak sampe warna kuning kecoklatan, angkat--Sementara lagi goreng ayam, kita siapkan sambel dulu, uleg semua cabe, dan bawang merah garam,sedikit gula dan penyedap, setelah agak halus kumpulin sambalnya di tengah cobek lalu siram dengan minyak panas bekas goreng ayam tadi lalu uleg lagi supaya rata--Masukan ayam goreng ke dalam cobek lalu penyet pake ulegan, siap di hidangkan--Selamat mencoba--', '3', '/id/resep/4472187-ayam-penyet-rumahan', NULL, NULL, NULL),
(11, 'Sop ayam', '1 kg ayam potong kecil kecil--1/2 kg ceker ayam bersihkan--1/2 kg kentang iris--1/2 kg wortel iris--1 mangkok makaroni (rebus)--2 batang daun bawang (sesuai selera)--4 batang daun seledri (sesuai selera)--Bumbu dihaluskan :--8 siung bawang merah--5 siung bawang putih--Tambahan :--1 sendok teh lada halus--secukupnya Garam--Penyedap rasa (bila Sun\'s saya pake gula aja)--', 'Tumis bawang merah dan bawang putih hingga harum--Masukkan potongan ayam dan ceker ke tumisan bumbu aduk rata--Pindahkan ke panci besar tanbahkan air secukupkan--Didihkan sampai ayam dan ceker cukup matang--Masukkan kentang dan wortel yang diiris tadi, tunggu sampai lembut--Masukkan macaroni yg sudah direbus--Taburkan lada bubuk dan garam, tes rasa--Terakhir masukkan daun bawang dan daun seledri--Siap dihidangkan, taburkan bawang goreng biar tambah maknyuss--', '3', '/id/resep/4472298-sop-ayam', NULL, NULL, NULL),
(12, 'Ayam suwir', '400 grm dada ayam--3 lembar daun jeruk--4 siung bawang putih--6 siung bawang merah--1 cm jahe--1 cm kunyit--secukupnya Garam dan gula--Minyak untuk menumis--', 'Rebus ayam sampai matang dan di suir suir.--Haluskan bawang putih, bawang merah, jahe, dan kunyit.--Panaskan minyak tumis bumbu halus, masukkan daun jeruk masak hingga harum tambahkan air secukupnya.--Masukkan ayam masak hingga matang.--', '0', '/id/resep/4472222-ayam-suwir', NULL, NULL, NULL),
(13, 'Ayam Koloke', '250 gr ayam fillet, potong-potong--2 sdm tepung bumbu serbaguna (larutkan dgn 75 ml air)--Pelapis:--4 sdm tepung terigu--1 sdm maizena--Bahan Saus--1 sdm butter / margarin--2 siung bawang putih, cincang halus--1 siung bawang bombai uk. Kecil (iris halus)--1/2 bh wortel (potong korek api)--1/2 bh timun (buang biji dan iris korek api)--1 btg daun bawang (potong2)--2 bh cabe merah (iris serong)--3 bh cabe rawit (iris serong)--3 sdm saus tomat--1 sdm saus tiram--1 sdt minyak wijen--1 sdt air lemon / jeruk nipis / cuka masak--250 ml air--Garam, lada, gula--1 sdt maizena (larutlan dgn 1 sdm air)--', 'Marinade ayam dgn tepung bumbu serbaguna yg sudah dilarutkan, aduk & disisihkan.--Siapkan bahan pelapis. Ambil potongan ayam & balur ke dalam bahan pelapis. Goreng dalam minyak panas sampai matang. Lakukan sampai habis.--Bahan saus: lelehkan butter, tumis duo bawang sampai harum. Masukkan wortel dan timun, tambahkan air, lalu masak sampai air mendidih. Masukkan duo cabe, saus tomat, saus tiram, minyak wijen, garam, gula, lada, air lemon, aduk rata. Masukkan larutan maizena, aduk sampai mengental. Terakhir masukkan daun bawang, matikan api supaya sayuran tidak over cook.--', '3', '/id/resep/4472309-ayam-koloke', NULL, NULL, NULL),
(14, 'Mie tulang ayam', '1/4 kg tulang ayam--1 bungkus kecil mie burung dara--5 siung bawang putih--3 siung bawang merah--7 cabe rawit--1 tangkai daun bawang--2 tangkai seledri--1 1/2 sdm merica bubuk--2 sdm saos cabe--3 sdm kecap manis--secukupnya Gula dan garam--Minyak untuk menumis--', 'Cuci bersih lalu rebus tulang ayam kurleb 10 menit. Lalu tiriskan--Rebus mie sampai setengah matang. Lalu tiriskan--Haluskan bawang merah, bawang putih dan cabe rawit--Tumis sampai harum bumbu halus dengan irisan seledri dan daun bawang. Lalu tambahkan merica bubuk, gula dan garam.--Masukkan tulang ayam, tunggu sampai bumbu meresap.--Masukkan mie, saos dan kecap. Lalu tumis sampai bumbu tercampur. Tambahkan gula dan garam jika diperlukan.--Mie tulang ayam siap dihidangkan.--', '1', '/id/resep/4472258-mie-tulang-ayam', NULL, NULL, NULL),
(15, 'Ayam Suir Bali (bemesere bali)', '1/2 kg dada ayam (rebus dahulu)--50 ml minyak goreng--Bumbu :--1/4 kg cabai merah--1/2 buah tomat--5 buah Cabe rawit--secukupnya Garam--secukupnya Gula jawa--1 sdt terasi bakar--1/2 perasan jeruk limo--3 buah daun jeruk purut--', 'Rebus ayam terlebih dahulu. Lalu, di suwir-suwir. (saya rebus karna kalau goreng, ayamny akan terasa keras dan kering)--Ulek halus bumbu, lalu icip2 rasa agar pas--Siapkan wajan, masukkan minyak goreng. Tunggu sampai panas, tuangkan bumbu--Stelah stengah matang, lalu masukan ayam yang sudah disuir.--Tunggu sampai agak meresap bumbuny. Masukkan perasan limo dan daun jeruk--Makanan siap dihidangkan. Simple dan enak--', '0', '/id/resep/4472532-ayam-suir-bali-bemesere-bali', NULL, NULL, NULL),
(16, 'Pindang ayam jadul', '1/2 kg ayam--5 btr bawang merah iris halus--10 buah cabe rawit iris halus--2 cm jahe iris halus--1 cm lengkuas iris halus--1/2 sdt kunyit halus--1 sdt asam jawa--1 sdt terasi bangka panggang--1 bh tomat potong 4--Secukupnya daun kemangi (me:gak ada)--', 'Tumis semua bumbu kecuali tomat dengan 2 sdm minyak,oseng sampai harum,tambahkan 1 liter air didihkan,kalau sudah mendidih masukkan ayam,tutup, masak sampai ayam matang, setelah ayam matang koreksi rasa,beri taburan tomat dan daun kemangi, sajikan hangat, segerrr abis--Selamat mencoba\nSemoga bermanfaat untuk semua--', '0', '/id/resep/4472100-pindang-ayam-jadul', NULL, NULL, NULL),
(17, 'Ayam Kacang Panjang Saos Hoisin', 'Bahan Daging--1 lembar paha atas/dada ayam--1 sdm kecap asin, arak beras, tapioka--Bahan saos--1 ikat Kacang panjang--2 siung baput cincang halus--3 cm jahe cincang halus--1 sdm saos hoisin--1 sdt kecap asin--0.5 sdt micin--100 ml air--Larutan tapioka--', 'Marinade daging dengan bahannya 30mnt.--Sebelum di tumis beri 1sdm minyak di daging ayam, aduk rata, lalu tumis agar tidak lengket di wajan. Matang, lalu angkat.--Tumis jahe 10detik, masukkan baput lalu tumis sampai wangi.--Masukkan kacang panjang, tumis sebentar lalu masukkan air, saos hoisin, kecap asin, micin. Tutup wajan, kecil kan api.--Tunggu 1-2menit, buka tinder tutup wajan, aduk sebentar lalu tutup lg 1-2menit.--Masukkan daging, aduk rata.--Masukan larutan tapioka agar saos mengental. Aduk rata lalu sajikan--', '2', '/id/resep/4472201-ayam-kacang-panjang-saos-hoisin', NULL, NULL, NULL),
(18, 'Tongseng ayam', '500 g daging ayam (potong2)--1250 CC santan dr 1 butir kelapa (pisahkan bagian yg kental)--3 lembar daun jeruk--3 lembar daun salam--1 ruas lengkuas (geprek)--1 batang serai (geprek)--20 buah cabe rawit hijau--1 batang daun bawang (potong serong)--1 buah tomat (potong2)--3 sdm kecap manis--1 buah kentang ukuran sedang (potong2)--Secukupnya kol (iris2 tebal)--Secukupnya garam,kaldu bubuk, gula pasir (sesuai selera masing2)--Bawang goreng untuk taburan--Secukupnya minyak untuk menumis--Bumbu halus ;--8 siung bawang merah--4 siung bawang putih--1 ruas jahe--1/2 ruas kunyit--1 sdt ketumbar--1/2 sdt merica--3 butir kemiri sangrai--3 buah cabai merah besar--', 'Siapkan semua bahannya.. panaskan minyak, masukkan bumbu halus.. masak hingga keluar aroma wangi,masukkan daun salam, daun jeruk, serai dan lengkuas.. kemudian masukkan potongan daging ayamnya.--Tuangkan santan encer, tunggu hingga daging ayam setengah matang.--Masukkan kentang, garam, gula, kaldu bubuk, dan kecap.--Masak hingga matang... Masukkan potongan kol dan juga cabai hijau.. lalu d susul dgn memasukkan santan kental, aduk2.. jgn sampai pecah santannya, tes rasa..--Setelah mendidih matikan api, masukkan potongan daun bawang dan tomat, lalu beri taburan bawang goreng.--', '1', '/id/resep/4471980-tongseng-ayam', NULL, NULL, NULL),
(19, 'Ayam penyet sambel kemangi', '400 gr dada ayam--1 ikat daun kemangi--1 buah timun uk sedang--1 bungkus bumbu racik tempe--bahan sambel--10 buah cabe merah--10 buah cabe rawit--3 siung bamer--2 siung baput--gula--garam--1/2 buah tomat merah--secukupnya terasi--secukupnya minyak utk menggoreng--air utk mengungkep ayam--', 'Potong ayam sesuai selera,cuxi bersih lalu ungkep dengan sesikit air dan campur dengan bumbu racik tempe,matang angkat--Panas kan minyak lalu goreng ayam hingga matang kecoklatan--Goreng sebentar semua bahan sambel nya,,uleg jadi satu tambahkan garam gula...tes rasa...kalo sudah oke..masukkan beberapa lmbar daun kemangi..giling agak kasar aja--Geprek ayam di atas ulek an,,susun di piring lalu letakkan sambel di atas ayam..susun irisan timun,dan juga kemangi. siap di santap dwngan nasi panas--', '0', '/id/resep/4472141-ayam-penyet-sambel-kemangi', NULL, NULL, NULL),
(20, 'Nugget Ayam Wortel', '250 gram daging ayam giling--1 buah wortel ukuran sedang--1/2 buah bawang bombay--2-3 siung bawang putih--3 batang daun bawang--2 butir telur ayam--100 gram tepung terigu (kurang lebih)--secukupnya Tepung roti--secukupnya Garam--secukupnya Lada--secukupnya Penyedap rasa ayam--Minyak goreng--', 'Potong-potong bawang bombay dan bawang putih. Tumis dengan sedikit minyak hingga harum. Angkat--Campurkan tumisan bawang dengan daging ayam giling dengan menggunakan blender atau food processor. Campur hingga bawang halus & tercampur rata. Tuang pada wadah yg telah disediakan untuk dicampur dengan bahan lain--Potong wortel jadi bagian yg kecil. Masukkan pada campuran daging giling sebelumnya--Potong daun bawang jadi bagian yg kecil. Masukkan pada adonan. Campur hingga rata--Masukkan 1 butir telur ayam. Campurkan--Masukkan tepung terigu perlahan-lahan dan campur hingga rata. Masukkan garam,lada dan penyedap rasa secukupnya.--Panaskan kukusan--Letakkan adonan pada cetakan yg telah disediakan. Masukkan pada kukusan yg telah dipanaskan sebelumnya. Tutup kukusan diberi kain agar air tidak menetes diadonan. Kukus kurang lebih 25-30 menit--Angkat adonan yg sudah matang dari kukusan. Biarkan agar sedikit dingin.--Setelah dingin potong-potong sesuai ukuran yg diinginkan.--Kocok lepas 1 butir telur ayam. Celupkan adonan nugget yg telah dipotong tadi kedalam telur. Kemudian gulingkan di tepung roti.--Ulangi langkah 11 hingga adonan nugget habis--Dinginkan pada freezer kurang lebih 1 jam agar tepung roti menempel dengan sempurna--Goreng nugget dengan minyak panas. Nugget ayam wortel siap disajikan.--Nugget yg masuk ke dalam freezer dapat bertahan maksimal 3-4 minggu--', '4', '/id/resep/4472084-nugget-ayam-wortel', NULL, NULL, NULL),
(22, 'Chicken Teriyaki', '500 gr Daging ayam iris memanjang--1 bh Bawang bombay, iris memanjang--1/2 sdt Gula--1/4 sdt Garan--150 ml Air--Minyak untuk menumis--Bumbu perendam :--3 sdm Saus teriyaki--2 sdm Saus tiram--1 sdm Kecap manis--1 sdt Minyak wijen--3 siung bawang putih, haluskan--2 cm Jahe, haluskan--1/4 sdt Merica--1/2 sdt Kaldu bubuk--', 'Campur daging  ayam dengan bumbu perendam,gula dan garam,diamkan dikulkas 1-2jam agar bumbu meresap.--Panaskan minyak tumis daging sampai matang tuangi air,masukan bawang bombay,masak sampai air agak menyusut,kentalkan dengan larutan maizena.--', '1', '/id/resep/4469586-chicken-teriyaki', NULL, NULL, NULL),
(23, 'Sop Ayam Garang Asam', '1/2 ayam--3 serai--3 cm jahe--20 cabe rawit merah--8 bawang putih--4 bawang merah--2 tomat hijau--2 jeruk nipis (boleh lebih)--4 daun jeruk--secukupnya daun bawang--secukupnya garam--secukupnya penyedap--secukupnya air matang--', 'Potong dan bersihkan ayam sesuai selera (kalo aku ku beri perasan jeruk nipis lalu diamkan dulu)--Bawang2an diiris kasar, serai dan jahe di geprek, cabe aku hanya iris 6pc sisanya aku biarkan utuh, tomat kupotong memanjang begitu juga daun bawang.--Panaskan minyak sedikit saja, masukkan bawang serai daun jeruk dan juga cabe diamkan hingga harum lalu masukkan air dan tunggu hingga mendidih. aetelah mendidih masukkan ayam--Tunggu ayam hingga setengah empuk bumbui dengan penyedap garam dan juga gula, masukkan perasan jeruk nipis dan tomat aduk hingga merata--Setelah koreksi rasa dan dirasa sudah pas dan ayam matang masukkan daun bawang. setelah itu selesai--', '2', '/id/resep/4466395-sop-ayam-garang-asam', NULL, NULL, NULL),
(24, 'Ayam panggang saos kecap', 'Bumbu ayam panggang ;--1 kg ayam potong sesuai selera--3 siung bawang merah,ulek halus--3 siung bawang putih,ulek halus--Sedikit kunyit,dan garam,ulek halus--Untuk olesan ayam ;--Kecap manis,saus tomat,sedikit minyak,dicampur--Saos kecap/cocolan ;--sesuai selera Kecap manis--5 siung bawang merah,iris melintang agak tebal--3 siung bawang putih,ulek halus--5 buah cabe rawit,ulek halus--2 buah tomat potong sesuai selera--Jeruk nipis (skip)--Arang untuk memanggang ayam--', 'Cuci bersih ayam dan tiriskan,campur dibumbu yang sudah dihaluskan,aduk rata,diamkan selama 15 menit,lalu kukus selama 20 menit/ sampai mateng--Sementara menunggu ayam dikukus,siapkan pemanggangan arangnya dulu untuk memanggang ayam--Keluarkan ayam yang sudah dikukus dan siap dipanggang diatas pemanggangan arang--Panggang ayam sambil diolesi dengan olesan, campuran kecap manis,saos tomat dan minyak,bolak balik ayam agar tidak gosong sambil diolesi sampai matang,angkat dan taroh dipiring saji--Campurkan semua bahan saos kecap/ cocolan nya diwadah(mangkok),tambahkan kecap manis secukupnya,aduk agar tercampur rata,dan beri perasan jeruk nipis--Ayam panggang dan saos kecap sudah siap dihidangkan bersama nasi hangat dan irisan timun sebagai pelengkap--', '0', '/id/resep/4471637-ayam-panggang-saos-kecap', NULL, NULL, NULL),
(25, 'Soto ayam kuah santan', '1/5 kg ayam (diungkep dulu,lalu digoreng)--2 bungkus santan kara--2 cm kunyit--1 cm jahe--secukupnya Lada--secukupnya Daun salam,lengkuas,daun jeruk dan sereh--5 siung bawang merah--5 siung bawang putih--Penyedap : gula,garam royko ayam--Bahan pelengkap:--iris Tomat--Daun bawang dan seledri--Bihun (rebus dulu)--Bawang goreng--Kol di potong tipis--Tahu goreng--Kerupuk--Bawang goreng--Jeruk nipis--Sambal (cabe rawit,bawang putih/merah di rebus dulu, diulek)--', 'Panaskan air rebus ayam hingga matang lalu tiriskan (air rebusan ayam bisa untuk kuah soto),lalu goreng ayam hingga matang--Haluskan bumbu bawang merah,putih,kunyit,jahe,lada,lengkuas sereh cukup digeprek dan tumis hingga matang--Masukan tumisan bumbu kedalam rebusan air,masukan daun salam,sereh dan daun jeruk--Berikan bumbu garam,gula penyedap rasa, daun bawang dan santan kara masak hingga matang--Sajikan soto selagi hangat bersama bihun dan pelengkap lainya--', '3', '/id/resep/4471748-soto-ayam-kuah-santan', NULL, NULL, NULL),
(26, 'Mie Geprek (Mie + ayam geprek)', '1 bungkus mie burung dara--1 ons dada ayam--tepung terigu--kubis--bawang putih--kecap--royco sapi--secukupnya garam--ebi--minyak wijen--saus tiram--lada bubuk--minyak goreng--air--cabe rawit--bawang merah--', 'Rebus mie burung dara, tiriskan--Geprek bawang putih 2 siung, tumis sampai harum--Masukkan minyak wijen 1 sendok teh. Tumis tumis sebentar bersama bawang--Masukkan air 1 gelas belimbing--Tambahkan kecap, ebi, garam, saus tiram, royco sapi, lada bubuk sesuai selera. Didihkan--Masukkan mie yang telah direbus. Masak sampai air menyusut--Tambahkan irisan kubis/kol. Aduk-aduk sebentar sampai air habis. Angkat--Cuci bersih ayam, potong jadi 2 bagian atau iris sesuai selera--Siapkan tepung kering. Caranya tambahkan garam dan royco sapi pada tepung. Takarannya sesuaikan dengan jumlah tepung--Siapkan celupan tepung basah. Caranya campurkan tepung dengan air sampai teksturnya cair tapi cukup kental--Masukkan ayam pada tepung kering. Lalu celupkan pada tepung basah. Masukkan ke tepung kering lagi. Remas-remas sampai tepung yang menempel ditangan terlepas dan menempel pada ayam--Goreng ayam pada minyak panas dengan api besar, agar teksturnya crispy. Masak sampai kecoklatan lalu angkat.--Sekarang membuat sambel bawang. Caranya bawang putih setengah siung + bawang merah 2 siung + cabe rawit sesuai selera diulek bersama garam dan gula. Tambahkan 1 sendok minyak lalu campur rata--Geprek ayam crispy tadi kedalam sambel bawang--Sajikan mie goreng dengan topping ayam geprek dan lalapan mentimun--Selamat mencoba--', '2', '/id/resep/4471771-mie-geprek-mie-ayam-geprek', NULL, NULL, NULL),
(27, 'Ayam Geprek', 'Fillet dada ayam khas dalam--Tepung bumbu kriuk--Baham Sambal:--7 buah rawit merah--10 buah cabai merah keriting--5 siung bawang putih--secukupnya garam--secukupnya kaldu jamur--', 'Letakkan sedikit tepung bumbu dalam wadah lalu beri air untuk bumbu rendaman ayam. Buat sedikit kental, lalu diamkan dalam freezer 10 menit--Ambil ayam dari bumbu rendaman, lalu baluri dengan tepung kering dan goreng hingga kecoklatan--Untuk sambalnya ulek semua bahan jadi 1 lalu tuangkan minyak panas.--Setelah itu masukan ayam yang sudah di goreng ke dalam cobek sambal dan ulek bersama.--', '1', '/id/resep/4471625-ayam-geprek', NULL, NULL, NULL),
(28, 'Ayam Asam Manis Rumahan citarasa Resto', 'Bahan--250 gram dada ayam, potong dadu--1 buah paprika merah/hijau--Sedikit nanas, potong dadu--1 bawang bombay--2 siung bawang putih, geprek--1 sdm minyak bawang utk menumis--Air dan tepung sagu, perbandingan 2:1--Saos asam manis:--4 sdm saos tomat--1 sdm saos sambal--1/2 sdt saos lea perrins--3 sdm gula pasir--1 sdt kaldu ayam--secukupnya garam--3 sdm kecap Inggris--1 sdt minyak wijen--1 sdm maggie seasoning--1 sdm saos raja rasa--Bumbu marinasi ayam:--1 sdt gula pasir--1 sdt garam--1 sdt kaldu ayam--1/2 sdt merica--', 'Marinasi ayam dengan bumbu marinasi, diamkan selama 10 menit--Tumis bawang bombay, bawang putih, paprika--Masukkan daging ayam yg telah dimarinasi--Masukkan saos asam manis--Masukkan campuran air dan tepung sagu--Aduk hingga mengental--Test rasa, tambahkan garam dan gula sesuai selera--', '6', '/id/resep/4471418-ayam-asam-manis-rumahan-citarasa-resto', NULL, NULL, NULL),
(29, 'Sop Balungan Ayam', 'Tulang dari 1 ekor ayam jowo, rebus dg api kecil--Bumbu ulek :--4 siung bawang putih--1/4 sdt merica bubuk--1/2 sdt pala bubuk--2 cengkeh--1 sdm garam(sesuaikan dg penggunaan air)--1/2 sdt kaldu jamur--1 sdt gula--Bahan sayur :--2 buah wortel, iris tipis--1 kentang ukuran kecil, potong dadu--1 bonggol sawi sendok--Secukupnya seledri dan daun bawang--Pelengkap : bawang merah goreng--', 'Cuci bersih tulang ayam, rebus dg api kecil hingga keluar kaldu bening, buang kotoran yang mengapung, setelah itu masukkan bumbu ulek. Biarkan mendidih.--Kemudian masukkan wortel, tunggu 3 menit masukkan kentang, tunggu 5 menit lalu cek rasa dan kematangan sayur, setelah pas baru masukkan sawi sendok, seledri, dan daun bawang. Aduk sebentar lalu matikan kompor.--Sajikan dengan taburan bawang merah goreng dan sambal kecap.--', '2', '/id/resep/4471258-sop-balungan-ayam', NULL, NULL, NULL),
(30, 'Sayap Goreng Bumbu Ngo Hiang', '1 kg sayap ayam bagian drum stick--2 sdm air jeruk nipis / lemon--1 sdt garam--1 sdm bumbu ngo hiang--3 tetes suclarose/stevia drop (boleh skip)--', 'Cuci sayap ayam, lalu dalam satu wadah masukkan sayap ayam beserta seluruh bumbu diatas, remas2--Simpan dalam kulkas semalaman hingga bumbu meresap--Goreng sayap ayam dengan minyak panas dan banyak hingga matang, sajikan--', '35', '/id/resep/4464881-sayap-goreng-bumbu-ngo-hiang', NULL, NULL, NULL),
(31, 'Semur ayam kampung', '1/2 kg ayam kampung--3 siung bawang putih--5 siung bawang merah--3 butir kemiri--1 ruas jahe--4 lembar daun jeruk--1 lembar daun salam--1 batang serai (digeprek)--Lengkuas--1/4 sdt kunyit bubuk--1/2 sdt ketumbar bubuk--1/4 sdt merica bubuk--3/4 sdt garam--1/2 sdt gula pasir--Sedikit royco--Secukupnya kecap manis--Secukupnya air kaldu ayam kampung--Secukupnya minyak goreng--', 'Potong ayam cuci lalu rebus sampai empuk. Haluskan bawang, kemiri, jahe.--Tumis bumbu halus sampai harum masukan serai, daun jeruk, daun salam, lengkuas. Masukan air kaldu, ayam, merica, garam, kunyit, ketumbar, kecap, royco. Masak hingga bumbu meresap dan empuk banget, cek rasa ya bun..--Semur ayam kampung udah matang...--Ini aku masaknya sampai empuk banget... gak alot ya.. gigitnya gak pakai gigi, pakai bibir aja udah bisa, hhheee... krn sebelum dibumbuin direbus dulu sampai empuk, setelah itu baru dibumbuin.--Selamat mencoba..--', '4', '/id/resep/4471433-semur-ayam-kampung', NULL, NULL, NULL),
(32, 'Ayam Tepung KFC super gurih', '4 potong ayam (paha atas atau paha bawah)--1 Sdt air lemon--Secukupnya black papper--Secukupnya garam--Bahan pelapis :--200 gr tepung terigu serba guna--30 gr tepung maizena--1 Sdt oregano--1 Sdt garam--1 Sdt masako ayam--1 Sdt bubuk cabai--Bahan pencelup :--2 sdm tepung terigu--1 Sdt bubuk cabai--1 Sdt garam--Secukupnya lada putih--Air es--', 'Marinade Ayam dengan air lemon, black papper Dan garam, diamkan kurleb 1 jam atau lebih--Campur semua bahan pelapis--Campur semua bahan pencelup--Lumuri Ayam dengan bahan pelapis, celupkan ke dalam bahan pencelup dan lumuri dengan bahan pelapis lagi. Lakukan 2-3 kali. Cubit cubit Bagian Luarnya agar hasilnya keriting--Panaskan minyak goreng--Goreng Ayam sampai matang, apinya Jangan terlalu besar agar matangnya merata hingga kebagian dalam--Sajikan bersama kentang, selada atau asparagus sesuai selera--Selamat mencoba--', '0', '/id/resep/4471388-ayam-tepung-kfc-super-gurih', NULL, NULL, NULL),
(33, 'Soto Ayam Surabaya', '1/2 Ekor Ayam--6 Siung Bawang Merah--4 Siung Bawang Putih--Secukupnya Ketumbar--Secukupnya Lada--1 Ruas Kunyit--1 Ruas Lengkuas--1 Ruas Jahe--1 Butir Kemiri--Daun Salam--Daun Jeruk--Gula--Garam--Penyedap Rasa (boleh pakai boleh tidak)--Daun Bawang--Kol--Tauge--Kentang--Telur Rebus--Sambal Rebus--', 'Haluskan semua bumbu kecuali lengkuas & Sereh--Tumis bumbu yg dihaluskan tadi hingga harum--Rebus ayam hingga terlihat kaldunya kemudian masukkan bumbu yg telah ditumis tadi--Icip & sajikan dengan kentang goreng, bihun, tauge & irisan tomat--', '4', '/id/resep/3452442-soto-ayam-surabaya', NULL, NULL, NULL),
(34, 'Ayam Suwir ala Bali / Ayam Sisit', '500 gram fillet ayam tanpa kulit--1 sdm minyak wijen--1 sdm kecap ikan--1 sdm saos tiram--1 sdm unsalted butter untuk menumis--Bumbu yang dihaluskan--10 siung bawang merah--5 siung bawang putih--1 ruas jari kencur--2 ruas jari kunyit--10 buah rawit merah atau sesuai selera--1 sdt udang rebon--1 sdt garam--', 'Rebus/Kukus Ayam lalu disuwir2, sisihkan--Tumis bumbu halus, tambahkan minyak wijen, kecap ikan, saos tiram--Masukkan suwiran ayam, aduk rata sampai tercampur dan kering (sesuai selera)--Siap dihidangkan--', '4', '/id/resep/4471237-ayam-suwir-ala-bali-ayam-sisit', NULL, NULL, NULL),
(35, 'Risoles rogut ayam', 'Bahan isian:--3 buah kentang, kukus dan tumbuk halus--1 buah wortel, diserut kasar--100 gr dada ayam rebus, suwir halus--2 sdm tepung terigu--secukupnya Lada bubuk--Secukupnya garam--100 ml susu cair--2 siung bawang putih, haluskan--50 gram keju cheddar parut--2 sdm minyak goreng--Bahan kulit:--250 gram tepung terigu--3 sdm margarine, dicairkan--2 butir telur--Secukupnya garam--secukupnya Air--100 gram tepung panir untuk membalur--', 'Aduk rata kentang kukus yang sudah dihaluskan, tepung terigu, susu cair sampai tidak menggumpal. Sisihkan--Tumis bawang putih yang sudah di haluskan sampai wangi, masukkan adonan kentang kukus yg sudah di campur susu dan terigu tadi.--Tambahkan keju parut, lada bubuk, ayam suwir, aduk cepat sampai kental. Angkat dan sisihkan--Untuk membuat kulit: campur tepung terigu, air, garam, 1 butir telur, aduk dengan pengocok telur agak tidak mengggumpal. Setelah rata masukkan margarine yg sudah dicairkan. Aduk rata kembali.adonan dibuat jangan terlalu kental.--Panaskan wajan anti lengket, dadar adonan sampai habis.--Ambil lembaran kulit, letakkan di tengah kulit dadar isian rogut, tutup sisi kanan kirinya--Sebelum di goreng, celupkan gulungan dadar yg sudah diisi tadi kedalam telur dan balurkan dengan tepung roti ulangi sekali lagi.--Panaskan minyak, goreng hingga kecoklatan.--Risoles siap disajikan hangat dengan cabai rawit atau saos cabai.--Selamat mencoba--', '7', '/id/resep/4466981-risoles-rogut-ayam', NULL, NULL, NULL),
(36, 'Ayam tepung', '1 kg ayam--500 gram tepung terigu--secukupnya Royco--6 siung bawang putih--1 sendok teh lada bubuk--1 ruas jahe--1 ruas kunyit--secukupnya Garam--Minyak goreng--2 butir telur ayam ambil putih nya aja--', 'Bersih kan ayam potong jadi 14--Haluskan,bawang putih,jahe,kunyit masuk an ke panci,masuk an ayam,tambah garam diam kan 30 menit(kalau aku di ungkep bentar bun tambah air segelas)--Campur terigu,royco untuk tepung kering--4sendok tepung terigu cair kan dengan 100 ml air,+ 2 butir putih telur kocok lepas,untuk celup an--Panas kan minyak goreng,ambil 1 potong ayam,masuk an ke tepung kering + masuk ke tepung celup + masuk ke tepung kering lalu goreng dengan minyak panas,api sedang sampai kecoklatan--Angkat dan bisa langsung di sajikan bunda--', '1', '/id/resep/4448850-ayam-tepung', NULL, NULL, NULL),
(37, 'Somay ayam bumbu kacang', '250 gr dada ayam--Kulit lumpia instan--150 gr terigu--100 gr kanji--4 siung bawang putih--1/2 sdm merica bubuk--1 sachet royco--Bumbu kacang--250 gr kacang--200 gr gula merah--1 sdt royco--1 sdm gula pasir--secukupnya Cabe--Larutan maizena--Kecap--Pelengkap ;--Gubis--Telur puyuh--Tahu putih--', 'Blender dada ayam tanpa tulang, bawang putih, merica bubuk, & royco..blender sampai lembut...blender dikasih es batu ya..--Tambahkan tepung terigu & kanji.aduk sampai merata--Ambil satu lembar kulit lumpia.isi dengan jeladren ayamnya..bentuk sesuai selera..lakukan hingga adonan habis--Kukus 20 menit sampai layu..kukus bersama pelengkapnya yaa..gubis & tahu putih... Gubis digulung2 lipat dengan tusuk sate..tahu putih dipotong2 dadu..--Telur puyuh rebus sampai matang..tiriskan--Buat bumbu ; goreng kacang sampai kecoklatan..--Blender kacang,cabe,& gula merah...tambahkan air secukupnya--Masukan bumbu kedalam kacang..masak hingga matang, tmbahkan gula pasir, penyedap rasa, tmbahkan larutan maizena agar kental--Potong2 somay,gubis,tahu,& telur puyuh..siram bumbu kacang ke atasnyaa...tmbahkan bawang goreng & kecap--', '4', '/id/resep/4470142-somay-ayam-bumbu-kacang', NULL, NULL, NULL),
(38, '.Ayam Kecap Cabe Ijo', '1 ekor ayam potong 8, bersihkan--Cabe ijo 15 buah, potong serong--Bawang bombay 1 siung, potong--Bawang putih 2 siung, cincang--garam--Gula pasir--Lada bubuk--1/2 sdt kaldu bubuk (aku pake royco)--4 sdm Kecap manis (aku pake bango)--Bumbu ungkep :--4 siung bawang merah--5 siung bawang putih--2 cm kunyit--2 cm jahe--2 cm lengkuas, geprek--1 batang serai--1,5 sdt ketumbar--2 buah kemiri--4 lbr daun jeruk--Garam--', '1. Ungkep ayam dengan bumbu ungkep kurleb 20 menit hingga bumbu meresap, sisihkan--2. Tumis bawang putih hingga harum, masukkan cabe ijo, bwg bombay, dan lada bubuk--3. Tambahkan air, gula pasir, kecap manis, tunggu hingga mendidih, masukkan ayam--4. Biarkan bumbu meresap, sambil ditambah garam kalau dirasa kurang asin--5. Kalau sudah mulai meresap, tes rasa, angkat.--', '9', '/id/resep/4470089-ayam-kecap-cabe-ijo', NULL, NULL, NULL),
(39, 'Ayam Masak Kluwek', '6 kluwek--2 ayam paha--5 sayap ayam--2 buah kemiri--2 buah cabe merah (opsional)--2 siung bawang merah--1 siung bawang putih--2-3 cm jahe--1 keping asam kering--1 sdm bubuk kunyit--Garam, Gula, Penyedap Rasa--secukupnya Air--', '(Cabe merah + bwg merah + bwg putih + kemiri + jahe) di tumbuk halus - masukan bubuk kunyit - aduk bentar--Tumis bumbu halus hingga wangi - masukan ayam aduk bentar--Kasih air - garam - gula - penyedap rasa - masukan kluwek - masukan asam keping--Masak hingga ayam matang & bumbu meresap--', '0', '/id/resep/4470099-ayam-masak-kluwek', NULL, NULL, NULL),
(40, 'Ayam Goreng Telur', '10 potong Paha Ayam(aku: 1 kg ayam. Potong_potong)--6 siung Bawang Putih--4 lembar Daun Jeruk--3 lembar Daun Salam--2 batang Serai--1 sendok teh Garam--1/2 sendok teh Ketumbar Bubuk--2 cm Kunyit--2 butir Telur Ayam--500 ml Air--', 'Cuci bersih paha ayam. \nhaluskan kunyit yang sudah dibakar,garam dan ketumbar bubuk. masukkan bumbu yang sudah dihaluskan,bawang putih yang digeprek,daun jeruk,daun salam dan serai ke dalam air. aduk rata. kemudian masukkan ayam sampai terendam. \nmasak hingga bumbu meresap. angkat dan diamkan hingga sedikit dingin.--Kocok lepas telur ayam. \nguling-gulingkan ayam yang sudah dibumbui sampai telur terbalur rata. siapkan minyak panas dan banyak agar ayam bisa tergoreng sempurna. goreng sampai berwarna kuning keemasan. tiriskan.\nSajikan dengan sambal tomat atau sambal terasi dan nasi hangat :)----', '17', '/id/resep/3934445-ayam-goreng-telur', NULL, NULL, NULL),
(41, 'Chicken Hainan & Nasi Hainan Simple Magic Com', 'Bahan untuk Ayam Hainan:--4 pcs Paha Ayam Utuh (Paha atas dan Paha bawah)--6 siung bawang putih--3 ruas jahe--1 batang sereh--2 lembar daun salam--1 jeruk nipis / lemon--1/2 siung bawang bombay--2 sdm kecap ikan--2 sdm minyak wijen--Sejumput garam--Air Matang--Kaldu ayam bubuk / block (opsional, saya tidak pake)--Bahan untuk Nasi Hainan:--3 Cup beras--4 siung bawang putih--2 ruas jahe--1 batang sereh digeprek--2 lembar daun salam--2 sdm minyak wijen--Sejumput garam--Kuah rebusan bumbu Chicken Hainan--Margarin--Bahan untuk Saus Hainan:--1 siung bawang putih parut--2 sdm kecap manis--2 sdm kecap asin--2 sdm minyak wijen--Bahan tambahan pelengkap:--Ketimun--Daun bawang--Bawang goreng--Emping--', 'Memasak Chicken Hainan: Cuci bersih ayam dan lumuri dengan sejumput garam dan perasan air jeruk nipis / lemon. Diamkan selama 10 menit. Sambil menunggu 10 menit, iris kasar bawang bombay, kemudian parut bawang putih dan jahe. Masak air hingga mendidih dipanci, dan jika sudah mendidih masukka bawang bonbay, bawang putih, jahe, sereh dan salam. Tunggu beberapa saat hingga harum, masukka ayam dan sedikit minyak wijen. Masak dengan api sedang selama kurang lebih 40menit.--Sebaiknya untum merebus Chicken Hainan ini airnya dibnyakin. Karena nanti kuah rebusan ayamnya ini digunakan untuk kuah chicken hainan dan untuk memasak nasi.--Memasak Nasi Hainan:. Cuci beras hingga bersih dan tiriskan. Kemudian parut bawang putih dan jahe. Selanjutnya lelehkan margarib pada wajan dengan api sedang dan kemudian tumis bawang putih, jahe, sereh dan salam. Tunis hingga harum dan layu. Beri sedikit air dan aduk2 hingga mendidih. Jika sudah mendidih, masukkan beras yg telah dicuci jedalam wajan, aduk rata hingga air dan bumbu tiris dan meresap. Angkay beras dan pindahlan ke Magic Com beserta bumbu2 yg sudah meresap tsb.--Masak beras dengan menggunakan air rebusan Chicken Hainan dan ditambahkan lg sejumput garam dan minyak wijen. Ayam yang sudah direbus tadi bisa juga ikut dimasukkan kedakam magi com agar lebih nikmat nasi hainan nya.--Membuat Saus Hainan: campurkan semua bahan didalam satu wadah, dan aduk rata.--Jika nasi sudah matang, Chicken Hainan dan Nasi Hainan ini siap disajikan dengan saus dan kuahnya. ditambahkan dengan topping daun bawang pada kuah, bawang goreng pada nasi dan ketimun sebagai pelengkap.--', '8', '/id/resep/4469533-chicken-hainan-nasi-hainan-simple-magic-com', NULL, NULL, NULL),
(42, 'Ayam Rica-rica super pedes', '1 ekor ayam potong--Bumbu:--5 buah cabai merah--20 buah cabai rawit--5 siung bawang putih--7 siung bawang merah--3 buah kemiri--1 sachet merica bubuk--1 sachet ketumbar bubuk--secukupnya gula merah--secukupnya kecap manis--secukupnya garam--secukupnya penyedap rasa--1 ruas kunyit--1 ruas jahe--1 ruas besar lengkuas--2 batang serai--3 lembar daun salam--2 lembar daun jeruk--secukupnya minyak goreng--secukupnya air--', 'Potong potong ayam cuci bersih tiriskan--Haluskan cabai merah rawit, bawang merah,putih, kemiri, dan kunyit.--Geprek jahe, lengkuas, serai, dan gula.--Tumis bumbu yang sudah di haluskan hingga harum, masukkan daun salam, jeruk dan bumbu yang digeprek kecuali gula merah.--Masukkan ayam, beri air secukupnya, ungkep 10 menit.--Masukkan merica, ketumbar, gula merah, kecap, garam dan penyedap rasa.--Ungkep selama kurang lebih 20 menit.--Tes rasa. siap sajikan.--', '21', '/id/resep/4426876-ayam-rica-rica-super-pedes', NULL, NULL, NULL),
(43, 'Ayam Goreng', '1 ekor ayam (cuci dan rebus sebentar untuk ngurangin lemaknya)--Bumbu :--5 siung bawang putih (geprek)--3 siung bawang merah (geprek)--1 ruas kunyit (geprek)--1/2 sdm ketumbar bubuk--2 lembar daun salam--1 lembar daun jeruk--1 batang serai (geprek)--secukupnya garam--', 'Siapkan sedikit air dalam panci, didihkan--Jika sudah mendidih masukkan semua bumbu bawang putih, bawang merah, kunyit, ketumbar, daun salam, daun jeruk, serai--Masukkan ayam, tambahkan garam, tes rasa, jika dirasa kurang garam bisa di tambahkan sesuai selera, lalu diamkan beberapa menit hingga air menyusut dan bumbu meresap, angkat dan sisihkan ayam dalam wadah kosong (Dinginkan)--Panaskan wajan dan minyak goreng, goreng ayam satu persatu hingga warna menjadi kuning kecoklatan, sajikan--', '1', '/id/resep/4469389-ayam-goreng', NULL, NULL, NULL),
(44, 'Ayam Cabe Ijo', '1 ekor ayam broiler potong 8 bagian--1 sdm air jeruk nipis--2 sdt garam--3 sdm minyak goreng utk menumis--2 lbr daun jeruk--1 batang sereh di geprek--Bumbu Halus :--8 butir bawang merah--5 siung bawang putih--10 buah cabe hujau besar--5 buah cabe rawit hijau--1 ruas jahe--1/2 ruas kunyit--3 butir kemiri--secukupnya Garam dan gula pasir--', 'Lumuri potongan ayam dengan air jeruk nipis dan garam, sisihkan, biarkan selama 15 menit.--Goreng ayam dengan minyak panas hingga kuning keemasan.--Tumis bumbu yg telah di haluskan masukan daun jeruk, dan serehnya, aduk rata masak terus hibgga bumbu matang dan keluar aromanya.--Masukan ayam yg telah di goreng sebelumya aduk rata, kalau perlu boleh tambahkan air sedikit agar bumbu meresap.--Cek rasanya, bila telah matang taruh di piring saji,ayam goreng cabe ijo siap disantap...----', '8', '/id/resep/4469122-ayam-cabe-ijo', NULL, NULL, NULL),
(45, 'Ayam fillet asam manis', '2 buah dada ayam tanpa tulang--100 gr tepung terigu--50 gr tepung maizena--1 putih telur--5 sdm saus tomat--1/2 sdm saus tiram--1 buah bawang bombay (iris)--2 siung bawang putih (cincang halus)--1 sdt garam--1 sdt gula pasir--1 sdt merica bubuk--', 'Cuci bersih dada ayam lalu potong kecil2 sesuai selera--Tambahkan garam, merica dan putih telur--Masukkan potongan ayam kedalam adonan tepung (tepung terigu + maizena + garam + lada). Atau bisa pakai tepung ayam instan.--Goreng dalam minyak panas selama 5-6 menit sampai berubah warna menjadi golden brown--Siapkan wajan untuk membuat saus asam manis--Tumis bawang putih dengan 3 sdm minyak goreng--Setelah harum masukkan bawang bombay--Tambahkan saus tomat, saus tiram dan setengah gelas air--Masukkan garam, gula dan merica bubuk, aduk sampai tercampur--Jangan lupa untuk koreksi rasa--Larutkan 1sdt maizena dengan air--Tambahkan larutan maizena sedikit demi sedikit hingga kekentalannya pas--Matikan api, siap disajikan--', '10', '/id/resep/4469254-ayam-fillet-asam-manis', NULL, NULL, NULL),
(46, 'Ayam ukep bumbu sederhana', '1 kg ayam broiler--8 siung bawang putih ukuran besar--1 sdm peres ketumbar--Kunyit--Garam--Gula--Air--', 'Cuci bersih ayam, boleh diberi perasan air jeruk nipisbiar ngga amis. Tp kebetulan aku ngga simpen jeruk nipis jd ya ngga pake. Ngga amis kok.--Ulek bawang putih, kunyit dan ketumbar hingga halus--Masukkan air ke wajan, nyalakan kompor. Masukkan setengah bumbu halus beri gula garam sesuai selera, masukkan ayam dilanjut dgn setengah bumbu sisanya.--Tutup wajan. Setelah 5 menit campur ayam dgn bumbunya. Tutup dan diamkan lg hingga dirasa matang.--Jika tidak langsung digoreng semua, bisa ditaruh di wadah tertutup. Tp tunggu dingin dulu yaa ayamnya. Trus masukkin kulkas deh.--Ini ayam yg udh digoreng--', '0', '/id/resep/4468662-ayam-ukep-bumbu-sederhana', NULL, NULL, NULL),
(47, 'Tongseng Ati Ampela Ayam', '2 potong hati ampela ayam yang masih dibalut usus--2 sdm minyak goreng--50 ml air--2 siung bawang putih--4 siung bawang merah--5 buah cabe rawit--3 buah cabe merah keriting--2 butir kemiri--1/4 sdt ketumbar bubuk--1/2 ruas jahe--1 ruas lengkuas geprek--1 lembar daun salam--1/4 sdt lada--1/2 sdt garam--1/2 sdt penyedap--2 sdm kecap manis--Sejumput pala bubuk--', 'Bersihkan ati ampelanya. Kemudian rebus, goreng setengah matang. Sisihkan!--Baput, bame, kemiri, cabe digoreng bentar lalu uleg--Panaskan minyak tumis bumbu, beri air dan masukkan ati ampelanya. Icip rasa. Tunggu hingga kuah agak menyusut. Sajikan :)--', '3', '/id/resep/3026845-tongseng-ati-ampela-ayam', NULL, NULL, NULL),
(48, 'Ayam penyet ala sy', '1/2 kg ayam potong2cuci bersh--1 sdm ktumbar bbuk--2 siung bwg puth--5 siung bwg merah--1 ruas laus--4 lmbr daun salm--secukupnya Garam--secukupnya Jeruk nipis--Bhn sambl ulek--secukupnya Cabe merah,cabe rawit--1 buah tomat merah besar--Secukupnya terasi bkar--Jeruk nipis atau jeruk limau--', 'Ungkep ayam dg bumbu yg sdh d hluskan hingga airnya hmpir kering--Setelh itu angkt.--Goreng ayam hingga matang,lalu tumbuk d a atas ulekkan.--Goreng semua bhn sambl lalu d uleg,setelh itu siram k ayam td--Jd deh siap d santap,iya jnga lupa tes rasa dl iy.--', '6', '/id/resep/4468798-ayam-penyet-ala-sy', NULL, NULL, NULL),
(49, 'Broccoli Rice with Grilled Chicken (menu sehat)', '1 bonggol Brokoli ukuran sedang / besar--500 gr Dada Ayam (bumbui dgn garam, lada, rosemary, kecap hitam)--1 buah Jamur King Oyster (sesuai selera)--50 gr Kentang (rebus terlebih dahulu)--Bawang putih cincang (untuk menumis)--Garam, lada hitam, gula / vetsin (untuk memperkuat rasa)--Rosemary dan thyme kering--', 'Halusnya brokoli dgn menggunakan Food Chopper / Food Processor sampai menyerupai oatmeal konsistensinya.--Tumis brokoli yg td dgn sedikit minyak dan bawang putih yg sdh dicincang halus. Beri garam, lada, dan sdkit gula. Sisihkan.--Panggang ayam di teflon yg panas sampai matang. Sisihkan.--Panggang kentang di teflon. Beri garam, lada, rosemary, dan thyme sedikit untuk memberikan rasa. Sisihkan.--Tumis jamur yg sdh dipotong2 dgn sdkit minyak dan bawang putih. Beri garam dan lada. Sisihkan. Jamur hanya dimasak sebentar saja. Karena kalu terlalu lama, jamur akan menyusut mjd kecil, dan kandungan vitamin serta proteinnya bs hilang.--Setelah semua sudah matang. Tinggal susun saja di kotak makan seperti di foto. Bisa lsg dimakan. Atau dijadikan bekal untuk adik atau anak ke sekolah. Kalau saya, besok paginya saya tinggal panaskan di microwave sebentar, baru dibawa deh sama adik ke sekolah. Atau bs jg dikukus sebentar saja sampai hangat.--Oh iya. Saya sgt suka mengkonsumsi jamur. Dan king oyster ini adalah jamur favorit saya. Memang harganya lebih mahal dibandingkan jamur2 yg lain. Sekitar 40rb 1 bungkusnya. Tp selain jamur ini sgt besar ukurannya, jamur ini jg hampir tidak mempunyai bau. Jd adik saya yg masih sekolah pun bisa makan jamur ini tanpa komplain krn jamur biasanya memiliki bau yg tidak enak. Berikut foto King Oyster Mushroom yg saya ambil di google (www.veggiecravings.com) untuk referensi.--', '8', '/id/resep/4467920-broccoli-rice-with-grilled-chicken-menu-sehat', NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `resep_masakan`
--
ALTER TABLE `resep_masakan`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
